// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateHabit(arg1:string,arg2:number):Promise<void>;

export function GetAllHabits():Promise<main.Habits>;
