// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHabit(arg1, arg2) {
  return window['go']['main']['App']['CreateHabit'](arg1, arg2);
}

export function GetAllHabits() {
  return window['go']['main']['App']['GetAllHabits']();
}
